name: connect-publish
on:
  push:
    branches: [main]

jobs:
  connect-publish:
    name: connect-publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        with:
          url: https://colorado.rstudio.com/rsc/
          api-key: ${{ secrets.CONNECT_API_KEY }}
          access-type: acl
          dir: |
            .:/shinytest2_gha

